### ISSUE TITLE
[docs]: create code of conduct & contributing guidelines

### ISSUE THREAD

**Issue by akebu6** [LambdaTest/test-at-scale-scripts#12]
Hello, I propose that the repo includes a Code of Conduct and a Contributing Guidelines files that will help contributors know what is required of them, how to conduct themselves and how they can make contributions that will be accepted in the repo.

I am not sure, what your thoughts on this are, but kindly let me know if I can work on both documents

**Comment by TKirtan** [comment]
I can work on this issue, Kindly assign me this.

**Comment by SparshKesari** [comment]
Hey @akebu6, thanks for picking this up.
Please make sure you follow our orgs guidelines. Please refer here:  https://github.com/LambdaTest/test-at-scale

**Comment by TKirtan** [comment]
> @TKirtan, sorry but I opened the issue so that I could work on it. You can find any other one or you can create your own issue to solve another problem :-)

Okay, No Problem with the thing.

**Comment by akebu6** [comment]
> > @TKirtan, sorry but I opened the issue so that I could work on it. You can find any other one or you can create your own issue to solve another problem :-)
> 
> Okay, No Problem with the thing.

Hope you find an issue to work on!

**Comment by TKirtan** [comment]
Yep, No problem
