### ISSUE TITLE
[docs]: create PR template

### ISSUE THREAD

**Issue by akebu6** [LambdaTest/test-at-scale-scripts#14]
The repo doesn't have a PR template that can be used to check if the contributor's PR meets the requirements of the repo.
I can add the PR and make it similar to the one here: https://github.com/LambdaTest/test-at-scale/blob/main/.github/pull_request_template.md

**Comment by AbhishekTiwari23** [comment]
I am ready to contribute, please assign.

**Comment by BajajAyush** [comment]
I am willing to do this, please assign it to me
